---
name: byu-news
description: byu-news
resources:
  - src: dist/**
    dest: ./
entrypoints:
  "byu-news.js": 'Examines browser support and downloads the appropriate component bundle'
  "byu-news.min.js": 'Minified - Examines browser support and downloads the appropriate component bundle'
  "byu-news.css": 'Main CSS file'
  "byu-news.min.css": 'Main CSS file'
docs: https://github.com/byuweb/byu-news
